core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("user/", include("auth_sys.urls")),
    path("materials/", include("materials.urls")),
    path('forum/', include("forum.urls")),
    path('announcement/', include("announcement.urls")),
    path('', include('news.urls')),
    path('events/', include('events.urls')),
    path('voting/', include('voting.urls')),
    path('calendarapp/', include('calendarapp.urls')),
    path('gallery/', include('gallery.urls')),
    path('diary/', include('diary.urls')),
    path('survey/', include('surveys.urls')),
    path('', include('calendarapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

voting/urls.py
from django.urls import path
from . import views

app_name = 'voting'

urlpatterns = [
    path('', views.poll_list, name='poll_list'),
    path('<int:poll_id>/', views.poll_detail, name='poll_detail'),
]

templates/base.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Group project</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <link rel="icon" type="image/png" href="{% static 'img/icon.png' %}">
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
    {% block css %}{% endblock %}
</head>
<body>
    {% include 'calendarapp/event_calendar.html' %}
    {% include "sidebar.html" %}
    <div class="main-content" id="main-content">
        {% block content %}
        {% endblock %}
    </div>

<footer class="footer">
<div class="footer-content">
    <p>© 2025 Group Project. All rights reserved.</p>
    <nav class="footer-nav">
    <ul>
        <li>About</li>
        <li>Contact</li>
        <li>Privacy Policy</li>
        <li>Terms of Service</li>
    </ul>
    </nav>
</div>
</footer>

                <!-- Тут скрипт для ВСЕГО если что, так что руками не трогать, писать Роману если что-->
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const sidebar = document.getElementById("sidebar");
        const mainContent = document.getElementById("main-content");
        const isCollapsed = localStorage.getItem("sidebarCollapsed") !== "false";
        sidebar.classList.add("no-transition");
        mainContent.classList.add("no-transition");
    
        if (isCollapsed) {
            sidebar.classList.add("collapsed");
            mainContent.style.marginLeft = "0px";
        } else {
            mainContent.style.marginLeft = "60px";
        }
    
        setTimeout(() => {
            sidebar.classList.remove("no-transition");
            mainContent.classList.remove("no-transition");
        }, 50);
    });
    

    function toggleSidebar() {
        const sidebar = document.getElementById("sidebar");
        const mainContent = document.getElementById("main-content");
        sidebar.classList.toggle("collapsed");
    
        if (sidebar.classList.contains("collapsed")) {
            mainContent.style.marginLeft = "0px";
        } else {
            mainContent.style.marginLeft = "60px";
        }
    
        localStorage.setItem("sidebarCollapsed", sidebar.classList.contains("collapsed"));
    }

    const themeSwitch = document.querySelector('.theme-switch');
    document.addEventListener('DOMContentLoaded', () => {
        const savedTheme = localStorage.getItem('theme') || 'light';
        document.body.classList.toggle('dark', savedTheme === 'dark');
        updateTheme(savedTheme);
    });

    themeSwitch.addEventListener('click', () => {
        const isDark = document.body.classList.toggle('dark');
        const newTheme = isDark ? 'dark' : 'light';
        localStorage.setItem('theme', newTheme);
        updateTheme(newTheme);
    });

    function updateTheme(theme) {
        if (theme === 'dark') {
        themeSwitch.classList.add('dark');
        } 
        else {
        themeSwitch.classList.remove('dark');
        }
    }


    const titleInput = document.getElementById('title');
    const titleCounter = document.getElementById('title-char-count');

    if (titleInput && titleCounter) {
        const titleMaxLength = titleInput.maxLength;

        titleInput.addEventListener('input', () => {
            const remaining = titleMaxLength - titleInput.value.length;
            titleCounter.textContent = ` ${remaining}/300`;
        });
    }


    document.addEventListener("DOMContentLoaded", function () {
        const modal = document.getElementById("imageModal");
        const modalImg = document.getElementById("modalImage");
        const closeBtn = document.getElementsByClassName("close")[0];

        document.querySelectorAll(".gallery-item img").forEach(img => {
            img.addEventListener("click", function () {
                modal.style.display = "block";
                modalImg.src = this.src;
            });
        });

        closeBtn.onclick = function () {
            modal.style.display = "none";
        };

        modal.onclick = function (event) {
            if (event.target === modal) {
                modal.style.display = "none";
            }
        };
    });

    function openModal(imageUrl, title, content, isApproved) {
    document.getElementById('modalImage').src = imageUrl;
    document.getElementById('modalTitle').textContent = title || '(No Title)';
    document.getElementById('modalContent').textContent = content || '(No Content)';
    document.getElementById('modalStatus').textContent = (isApproved === 'False') ? '⏳ Waiting for approval' : '';
    document.getElementById('imageModal').style.display = 'flex';
    }

    function closeModal() {
    document.getElementById('imageModal').style.display = 'none';
    }

    function toggleReplyForm(postId) {
    const form = document.getElementById(`reply-form-${postId}`);
        if (form.style.display === "none" || form.style.display === "") {
            form.style.display = "block";
        } else {
            form.style.display = "none";
        }
    }
    
    function wrapText(before, after) {
        const textarea = document.getElementById('content');
        const start = textarea.selectionStart;
        const end = textarea.selectionEnd;
        const selected = textarea.value.substring(start, end);
        const replacement = before + selected + after;
    
        textarea.setRangeText(replacement, start, end, 'end');
        textarea.focus();
    }

    const simplemde = new SimpleMDE({
        element: document.getElementById("content"),
        spellChecker: false,
        status: false,
        toolbar: [
          "bold", "italic", "heading", "|",
          "unordered-list", "ordered-list", "|",
          "link"
        ],
    });

</script>
</body>
</html>

templates/form.html
{% extends 'base.html' %}
{% block content %}
<div class="auth-content">
    <div class="form-wrapper">
        <h2 class="form-title">{% block title %}{% endblock %}</h2>
        <form method="post" class="styled-form" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-field">
                    {{ field.label_tag }}
                    {{ field }}
                    <div class="field-error">{{ field.errors }}</div>
                </div>
            {% endfor %}
            <button type="submit" class="auth-btn">
                {% block button %}{% endblock %}
            </button>
        </form>
    </div>
</div>
{% endblock %}

templates/side_menu.html
{% load static %} 
{% if request.user.is_authenticated %}
    <div class="sidebar" id="sidebar">
        <button class="theme-switch"></button>
        <ul>
            <li><a href="{% url 'logout' %}">🔐 Logout</a></li>
            <li>⚙️ Settings(🚧)</li>
            <li><a href="{% url 'announcements' %}">📣 Announcements</a></li>
            <li><a href="{% url 'forum_main_page' %}">💬 Forum</a></li>
            <li><a href="{% url 'forum_main_page' %}">📖 Diary(🚧)</a></li>
            <li><a href="{% url 'news_list' %}">📰 News</a></li>
            <li><a href="#">👨‍🎓 profile(🚧)</a></li>
            <li><a href="{% url 'voting:poll_list' %}">🗳️ Голосування</a></li>
        </ul>
    </div>
{% else %}
    <div class="sidebar" id="sidebar">
        <button class="theme-switch"></button>
        <ul>
            <li><a href="{% url 'user_login_menu' %}">🔐 Login</a></li>
            <li>⚙️ Settings(🚧)</li>
            <li><a href="{% url 'announcements' %}">📣 Announcements</a></li>
            <li><a href="{% url 'forum_main_page' %}">💬 Forum</a></li>
            <li><a href="{% url 'forum_main_page' %}">📖 Diary(🚧)</a></li>
            <li><a href="{% url 'news_list' %}">📰 News</a></li>
        </ul>
    </div>
{% endif %}

<button class="toggle-btn" onclick="toggleSidebar()">☰</button>

templates/sidebar.html
{% load static %} 
{% if request.user.is_authenticated %}
    <div class="sidebar" id="sidebar">
        <button class="theme-switch"></button>
        <ul>
            <li><a href="{% url 'request_user_details' %}">👨‍🎓 Profile</a></li>
            <li><a href="{% url 'announcements' %}">📣 Announcements</a></li>
            <li><a href="{% url 'news_list' %}">📰 News</a></li>
            <li><a href="{% url 'forum_main_page' %}">💬 Forum</a></li>
            <li><a href="{% url 'event_list' %}">📅 Events</a></li>
            <li><a href="{% url 'voting:poll_list' %}">🗳️ Голосування</a></li>
            <li><a href="{% url 'subjects' %}">📖 Diary (🚧)</a></li>
            <li><a href="{% url 'survey_list' %}">📋 Survey</a></li>
            <details>
                <summary>
                    📝 Materials
                </summary>
                <ul>
                    <li>
                        <a href="{% url 'subject_list' %}">View subjects</a>
                    </li>
                    <li>
                        <a href="{% url 'subject_create' %}">Create subject</a>
                    </li>
                    <li>
                        <a href="{% url 'material_create' %}">Create material</a>
                    </li>
                </ul>
              </details>
            <li>⚙️ Settings (🚧)</li>
        </ul>
    </div>
{% else %}
    <div class="sidebar" id="sidebar">
        <button class="theme-switch"></button>
        <ul>
            <li><a href="{% url 'user_login_menu' %}">🔐 Login</a></li>
            <li><a href="{% url 'news_list' %}">📰 News</a></li>
            <li><a href="{% url 'forum_main_page' %}">💬 Forum</a></li>
            <li><a href="{% url 'event_list' %}">📅 Events</a></li>
            <li><a href="{% url 'subjects' %}">📖 Diary (🚧)</a></li>
            <li><a href="{% url 'survey_list' %}">📋 Survey</a></li>
            <li>⚙️ Settings (🚧)</li> 
        </ul>
    </div>
{% endif %}

<button class="sidebar-toggle-btn" onclick="toggleSidebar()">☰</button>